### ISSUE TITLE
mobile app not working with auth

### ISSUE THREAD

**Issue by shivno** [superdesk/superdesk-core#1034]
hi,

i wanted to try out the ios liveblog reporter app. upon login i get an notimplemented error, which comes from
apps/auth/service.py line 30:
`        raise NotImplementedError()
`
and i cant figure out how this can even work? is the mobile app non-functional? the server works fine with the webinterface

**Comment by petrjasek** [comment]
pls ask on https://github.com/liveblog/liveblog we're not working with the app here
