### ISSUE TITLE
Question - Specific questions around superdesk-core

### ISSUE THREAD

**Issue by DarkBlaez** [superdesk/superdesk-core#1105]
How does superdesk-core (this repo) fit in with the main superdesk repo? Originally I think superdesk-content-api (pubapi) was used and now depreicated. The README is a bit of a misdirect in that it references the superdesk repo for installation. Yet superdesk-core is not referenced. Likewise the documentation is sparse and Overview/Installation sections are missing. I have inquired and opened issues prior which I was able to get the clarification needed.

Here are my questions:

1. If superdesk-content-api is depricated where is this functionality now kept?
2. How does superdesk-core fit in? and what are the install instruction deltas if superdesk-core is to be incorporated. The "refer to superdesk repo" for installation does not indicate how this fits in.  What superdesk-core looks like to me is a refactor and an emergence of a new architecture for superdesk?

Thanks
DB

**Comment by petrjasek** [comment]
hi,

we superdesk repository for deployment config and some client custom parts, the common code is in superdesk-core for backend and superdesk-client-core for client. then these are required from superdesk via server/requirements.txt and client/package.json files.

regarding content-api - it's now part of superdesk-core as well, so there is no need to install it separately, 
and it runs its [own process](https://github.com/superdesk/superdesk/blob/master/server/Procfile#L5) by default
