### ISSUE TITLE
 Failed to instantiate module superdesk-publisher

### ISSUE THREAD

**Issue by netmonk** [superdesk/superdesk-core#1489]
I just did a fresh install of superdesk-core on on vps. And installed superdesk-publisher on a second vps. 
When i try to activate superdesk-publisher in superdesk-core following [](https://superdesk-publisher.readthedocs.io/en/latest/manual/getting_started/superdesk-superdesk-publisher-setup.html#update-configuration-file)
i get this error : 
![screenshot from 2019-01-21 21-51-44](https://user-images.githubusercontent.com/3428684/51498500-07ea3e00-1dc7-11e9-9226-324b1b8f11b1.png)
seems ant the superdesk welcome page is just pure blank, printing nothing in the tab.

**Comment by netmonk** [comment]
```
root@sd-66142:/opt/superdesk/client/dist# cat config.js
window.superdeskConfig = {
    apps: ['superdesk-publisher'],
    publisher: {
        protocol: "http",
        tenant: 'ki1kzs', // subdomain
        domain: '62.210.222.130', // IP address or domain name of your server where Superdesk Publisher is installed
        base: 'api/v1'
    },
};

```
```
root@sd-66142:/opt/superdesk/client/dist# cat config.ec23ae24.js
window.superdeskConfig = {
    apps: ['superdesk-publisher'],
    publisher: {
        protocol: "http",
        tenant: 'ki1kzs', // subdomain
        domain: '62.210.222.130', // IP address or domain name of your server where Superdesk Publisher is installed
        base: 'api/v1'
    },

};

```

This is the content i added on both config.js files on superdesk vps

**Comment by petrjasek** [comment]
hi, you should also add `superdesk-publisher` to `client/package.json` and run npm install, grunt build again and it should work

**Comment by netmonk** [comment]
```
{
    "name": "superdesk",
    "license": "GPL-3.0",
    "dependencies": {
        "superdesk-core": "1.27.1",
        "superdesk-publisher": "superdesk/superdesk-publisher"
    }
}
```

This is what i added, run `nmp install` and `grunt build` i still get same error

**Comment by netmonk** [comment]
Do you need more info ?

**Comment by petrjasek** [comment]
can you paste your `client/superdesk.config.js` here?

**Comment by netmonk** [comment]
of course 
```
/**
 * This is the default configuration file for the Superdesk application. By default,
 * the app will use the file with the name "superdesk.config.js" found in the current
 * working directory, but other files may also be specified using relative paths with
 * the SUPERDESK_CONFIG environment variable or the grunt --config flag.
 */
module.exports = function(grunt) {
    return {
        defaultRoute: '/workspace/personal',

        view: {
            timeformat: 'HH:mm',
            dateformat: 'DD.MM.YYYY'
        },

        features: {
            preview: 1,
            swimlane: {columnsLimit: 4},
            noTakes: true,
            editor3: true,
            validatePointOfInterestForImages: false,
            editorHighlights: true,
            noPublishOnAuthoringDesk: true,
            noMissingLink: true
        }
    };
}
```;

**Comment by petrjasek** [comment]
you should put this config:
```
    apps: ['superdesk-publisher'],
    publisher: {
        protocol: "http",
        tenant: 'ki1kzs', // subdomain
        domain: '62.210.222.130', // IP address or domain name of your server where Superdesk Publisher is installed
        base: 'api/v1'
    },
```
in that `client/superdesk.config.js` otherwise it won't be used during build, those files in dist don't affect the build, those are generated

**Comment by netmonk** [comment]
What should be the value of `tenant` ? 
Is it the tenant id generated during publisher installation ?

**Comment by netmonk** [comment]
after adding the block to superdesk.config.js i can access to superdesk without error. 

But i cannot see the `publisher` sub menu as expected. 
![screenshot from 2019-01-25 10-09-03](https://user-images.githubusercontent.com/3428684/51736010-4a42a200-2089-11e9-89b8-1a5ff82e5cb4.png)

**Comment by petrjasek** [comment]
I think it's that last icon in gray sidebar,
@ahilles107 can you answer those tenant questions?

**Comment by netmonk** [comment]
Well i clicked the icon but it cannot reach the publisher : 
![screenshot from 2019-01-25 10-33-21](https://user-images.githubusercontent.com/3428684/51737404-cbe7ff00-208c-11e9-9774-aea2ca5fe005.png)

**Comment by ahilles107** [comment]
What do You have in browser console log (or network tab)?

**Comment by netmonk** [comment]
i see it was trying to reach `ki1kzs.62.210.222.130`, so i emptied the tenant value and it worked.

**Comment by netmonk** [comment]
![screenshot from 2019-01-25 10-50-22](https://user-images.githubusercontent.com/3428684/51738271-0783c880-208f-11e9-8be1-9f04b4831b8c.png)
This notification.js error trying to connect to `0.0.0.0:5100` is quite annoying. how to get ride of it ?

**Comment by netmonk** [comment]
Good morning, i would like to succeed in installing the publisher. Can someone reply and try to solve thoses issue ?

**Comment by petrjasek** [comment]
hi, run the grunt build with your websocket address like:
```
$ grunt build --ws=ws://backofficesd.citoyx.com/ws
```

**Comment by netmonk** [comment]
Ok the failed connection to notification disappeared. Great. 
But still i have issue with connecting to publisher : 
![screenshot from 2019-01-31 11-40-58](https://user-images.githubusercontent.com/3428684/52049101-30073900-254d-11e9-90df-1d400a9d2c43.png)

What is the file used as `config.publisher` ?

**Comment by netmonk** [comment]
Damn each time i run a grund build, all config files in dist subfolder are replaced.

**Comment by petrjasek** [comment]
yep you should make the config in `client/superdesk.config.js` and not touch anything in build

**Comment by kumarincloud** [comment]
![image](https://user-images.githubusercontent.com/44183412/75848707-ef8d8500-5e08-11ea-9afa-6371b86c9e65.png)

i have installed superedesk and publisher on 2 different node and done the configuration as per provided guide line on github , but not able to view publisher page its showing blank
attached error , pls suggested to fix this

**Comment by petrjasek** [comment]
@takeit any idea?

**Comment by takeit** [comment]
@kumarincloud what are the errors in the browser's console?

**Comment by kumarincloud** [comment]
this one is the error
{"code":405,"message":"No route found for \"GET \/api\/v1\/auth\/superdesk\/\": Method Not Allowed (Allow: POST)"}
