### ISSUE TITLE
MongoDB database was dropped by the system

### ISSUE THREAD

**Issue by mikeavena** [superdesk/superdesk-core#1572]
The 'superdesk' MongoDB database was dropped without user interaction, presumably by the system. The database still existed, but had no collections other than the lock file. I discovered this when I was unable to log into our production system because the user was not found. I then checked the database to find it had nothing in it.

This exact same issue occurred on 3 separate and unconnected instances of Superdesk - our production system and two test instances. No single person had access to all of these instances, so it couldn't have been someone going around and dropping the databases.

I restored a backup from 10 days ago and all of my data was there, so I know for sure that the issue happened between March 23 and this morning. I have another backup from 3 days ago (March 30) that shows a significantly higher disk space usage than this morning's usage, so I can assume the database was actually dropped within the past 3 days, but I did not test it. We do not have backups for the test instances.

The only common thing between these three instances is that they were all running on Linode nodes (however, each one is under separate Linode accounts). Other than that, I have no idea why three separate databases were all suddenly dropped.

**Comment by petrjasek** [comment]
hi, do you have any server logs from that period you could share?

**Comment by mikeavena** [comment]
I've tried to recover any systems logs that would point to what happened but no luck.

**Comment by mikeavena** [comment]
After further analysis, we're almost certain it was due to incorrect security configurations on our part. I'll close this unless I find something else.
