### ISSUE TITLE
Mail server env params

### ISSUE THREAD

**Issue by RQmobile** [superdesk/superdesk-core#2144]
Some mail servers configured to allow all emails to be send limited only by the IPs of the sender. User name and password are not required. In this case, it would be impossible to set MAIL_DEFAULT_SENDER and _MAIL_FROM.
My suggestion is to set those params from environment variables.
Currently, MAIL_DEFAULT_SENDER and _MAIL_FROM uses MAIL_USERNAME variable
MAIL_DEFAULT_SENDER = MAIL_DEFAULT_SENDER or "superdesk@localhost"
_MAIL_FROM = env("MAIL_FROM", MAIL_DEFAULT_SENDER)

**Comment by petrjasek** [comment]
hi, makes sense, would you like to send a PR?

**Comment by RQmobile** [comment]
Would be great, however, I don't have rights for this
