### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by JamieSlome** [superdesk/superdesk-core#2364]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@b4zinga) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by petrjasek** [comment]
Hello,

thanks for the notification, added the info as you requested.

Petr

**Comment by JamieSlome** [comment]
@petrjasek - great, we will get an e-mail sent over shortly with more details 👍 

Just for reference, the report can also be found directly here:
https://huntr.dev/bounties/b9ea9157-02bd-4fab-bb32-fe1d717c1367/

It is currently private and only accessible to maintainers with repository write permissions :)
