### ISSUE TITLE
Superdesk Caching

### ISSUE THREAD

**Issue by petrjasek** [superdesk/superdesk-core#487]
we need caching in superdesk to keep performance under load. Lets gather requirements and do some research before implementing:

### Requirements
- cache db/elastic queries
- cache file reading/parsing
- share cache between requests/celery workers
- invalidating cache by tag
- per request/session cache

### Required Backends
- Redis
- Memcached

### Libraries
- Flask-Cache
- Werkzeug cache module
- Hermes
- Beaker

## API

there should be a decorator for caching, something like:

```
from superdesk.cache import cache

@cache(ttl=600)
def do_something(foo):
    ...

class CachedService(Service):

    @cache(ttl=30, tags=['activity'])
    def get_activity(self, user_id):
        ...
```

this way we can wrap db/elastic/etc calls and cache it.

Pls let me know what other requirements/libs/etc you can think of and I will look into it and evaluate.
/cc @mugurrus @jerome-poisson @ioanpocol @mdhaman @akintolga @marwoodandrew @hlmnrmr

**Comment by akintolga** [comment]
:+1:  I think this improvement will improve the performance of the system. 

- Initially we can implement caching to not-frequently-changing collections like users, roles, desks, stages, subscribers, vocabularies ...
- Even when we use Redis for caching between workers or requests, we could use in-request caching to reduce redundant find-one's ...

These points are reiterating the obvious so overall I like the presented plan...
