### ISSUE TITLE
SDESK-1490: Content schema for custom fields

### ISSUE THREAD

**Issue by petrjasek** [superdesk/superdesk-core#958]
we can put custom fields within an object, in this case it's called `extra` in item schema.
this way we don't have to change schema with new fields:
```
{
  "type": "text",
  "extra": {
    "tweet": "tweet version"
  }
}
```
in ninjs output it can go into `body_` prefixed fields which would be according to [standard](http://www.iptc.org/std/ninjs/ninjs-schema_1.1.json), or we can keep it within extra field as superdesk extension. but I think in general we would have custom outputs per client to handle such fields.
```
{
  "type": "text",
  "body_tweet": "some short version of item"
}
```
metadata with controlled vocabularies can be exported as `person`, `event`, `place`, `organisation` or default `subject` field in [NINJS](http://www.iptc.org/std/ninjs/ninjs-schema_1.1.json)
```
{
  "type": "text",
  "subject": [
    {"scheme": "medtop", "code": "01000000"},
    {"scheme": "age", "code": "15-19"},
    {"scheme": "age", "code": "20-27"},
    {"scheme": "audience", "code": "kids"}
   ]
}
```

**Comment by hlmnrmr** [comment]
For internal purposes, the `extra` way looks fine. In regards to the outputs though, I think we should keep it quite literal. I wouldn't try to fit custom fields (associated to a controlled vocabulary) within standard ninjs fields. We don't know what kind of custom fields people are going to create, it could be things like the examples in the JIRA ticket (e.g. Age Range, Target Audience, Industry, Expected Reaction). None of those naturally fit into either `person`, `event`, `place`, `organisation` or `subject`. What about making use of specific extensions, ninjs allows for that http://dev.iptc.org/ninjs-How-To-create-provider-specific-extensions

In such case, we would rather output something like:
```
{
  "type": "text",
  "age_range": [
    ...
  ],
  "expected_reaction": [
    ...
  ]
}
```

**Comment by petrjasek** [comment]
imo there is an issue here because with every new field you change schema, so you have to adjust the receiving system. while if you put this into subject it's generic
